# Generated by Django 2.1.2 on 2018-10-17 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('self_list', models.TextField(null=True)),
                ('medicine_list', models.TextField(null=True)),
                ('dos_list', models.TextField(null=True)),
                ('donts_list', models.TextField(null=True)),
                ('self_care', models.CharField(max_length=120)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Symptom',
        ),
    ]
