# Generated by Django 2.1.2 on 2018-10-17 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20181017_2231'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Issue',
        ),
    ]
